[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "st_package_reviewer"
version = "0.4.0-dev"
description = "Review packages for Sublime Text."
authors = ["FichteFoll <fichtefoll2@googlemail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/packagecontrol/st_package_reviewer"
repository = "https://github.com/packagecontrol/st_package_reviewer"
packages = [
    { include = "st_package_reviewer" },
    { include = "tests", format = "sdist" },
]
classifiers = [
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Quality Assurance',
    'Operating System :: OS Independent',
    'Environment :: Console',
]

[tool.poetry.scripts]
st_package_reviewer = "st_package_reviewer.__main__:main"


[tool.poetry.dependencies]
python = "^3.5"
pyperclip = "^1.7.0"
"github3.py" = "^1.3.0"

[tool.poetry.dev-dependencies]
coverage = "^5.0.4"
flake8 = "^3.7.9"
flake8-docstrings = "^1.5.0"
pytest = "^5.4.1"
pytest-watch = "^4.2.0"
tox = "^3.14.6"
